#!/bin/sh

# set -e

# Reading configuration file from filesystem and live-media
for _FILE in /etc/hybrid/boot.conf /etc/hybrid/boot/*
do
	if [ -e "${_FILE}" ]
	then
		. "${_FILE}"
	fi
done

for _COMONENT in /lib/hybrid/boot/????-*
do
	if [ -e "${_COMONENT}" ]
	then
		. ${_COMONENT}
	fi
done
