#!/bin/sh

set -e

case "${1}" in
	purge)
		rmdir --ignore-fail-on-non-empty /etc/hybrid/boot > /dev/null 2>&1 || true
		rmdir --ignore-fail-on-non-empty /etc/hybrid > /dev/null 2>&1 || true
		;;

	remove)
		if [ -x /usr/sbin/update-initramfs ] && [ -e /etc/initramfs-tools/initramfs.conf ]
		then
			update-initramfs -u
		fi
		;;
		
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
